---
apiVersion: v1
kind: Template
metadata:
  name: sandbox
objects:
  - apiVersion: cloud.redhat.com/v1alpha1
    kind: Frontend
    metadata:
      name: sandbox
    spec:
      envName: ${ENV_NAME}
      title: Developer Sandbox
      deploymentRepo: https://github.com/RedHatInsights/developer-sandbox-ui
      API:
        versions:
          - v1
      frontend:
        paths:
          - /apps/remediations
      image: ${IMAGE}:${IMAGE_TAG}
      navItems:
        - appId: "sandbox"
          title: "Developer Sandbox"
          href: "/openshift/sandbox"
      module:
        manifestLocation: "/apps/sandbox/fed-mods.json"
        modules:
          - id: "sandbox"
            module: "./RootApp"
            routes:
              - pathname: /openshift/sandbox
parameters:
  - name: ENV_NAME
    required: true
  - name: IMAGE_TAG
    required: true
  - name: IMAGE
    value: quay.io/cloudservices/sandbox
